config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/dashboard', to: 'home#dashboard'

  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET request to /contacts/new
  def new
    @contact = Contact.new
  end

  # GET request to /contacts/:id
  def show
    # finding a contact by id from the database
    @contact = Contact.find(params[:id])
  end

  # GET request to /contacts
  def index
    # getting all contacts from the database
    @contacts = Contact.all
  end

  # POST request to /contacts
  def create
    # Mass assignment of form fields into Contact object
    # contact_prams is a method defined below
    @contact = Contact.new(contact_params)

    # Save the Contact object to the database
    if @contact.save
      # On success: redirect to the show contact page (we will implement that shortly)
      redirect_to @contact
    else
      # On failure: render the new contact form so the user can fix the errors
      render :new, status: :unprocessable_entity
    end
  end

  # GET request to /contacts/:id/edit
  def edit
    @contact = Contact.find(params[:id])
  end


  # PATCH/PUT request to /contacts/:id
  def update
    @contact = Contact.find(params[:id])

    # Mass assignment of form fields into Contact object
    # contact_prams is a method defined below
    if @contact.update(contact_params)
      redirect_to @contact
    else
      render :edit
    end
  end

  # DELETE request to /contacts/:id
  def destroy
    contact = Contact.find(params[:id])
    # Destroying the contact from the database
    contact.destroy

    redirect_to contacts_path
  end


  private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :phone)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
    # Nothing inside this method
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with model: @contact, local: true, class: 'mb-5' do |form| %>

  <!--form.label is a rails helper method that creates a label for a form field-->
  <div class="field">
    <%= form.label :first_name, class: 'form-label'%>
    <!--form.text_field is a rails helper method that creates a text field for a form-->
    <%= form.text_field :first_name, class: 'form-text-input', placeholder: 'Enter first name'  %>
  </div>

  <div class="field">
    <%= form.label :last_name, class: 'form-label' %>
    <%= form.text_field :last_name, class: 'form-text-input', placeholder: 'Enter last name' %>
  </div>

  <div class="field">
    <%= form.label :email, class: 'form-label' %>
    <%= form.text_field :email, class: 'form-text-input', placeholder: 'Enter email address' %>
  </div>

  <div class="field">
    <%= form.label :phone, class: 'form-label' %>
    <%= form.text_field :phone, class: 'form-text-input', placeholder: 'Enter phone number' %>
  </div>

  <div class="actions">
    <!--form.submit is a rails helper method that creates a submit button for a form
    submitting the form will send a POST request to the url specified in the form_with method-->
    <%= form.submit 'Save', class: 'btn-primary' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<!-- app/views/contacts/edit.html.erb -->

<h1 class="col-start-1 col-end-3 mb-5">Edit Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path, class: 'btn-secondary' %>

app/views/contacts/index.html.erb
<!-- contacts/index.html.erb -->

<div class="grid grid-cols-6 gap-4 mb-10">
  <!-- Display the page title -->
  <h1 class="col-start-1 col-end-3">All Contacts</h1>

  <!-- Link to create a new contact -->
  <%= link_to 'New Contact', new_contact_path, class: 'col-end-7 col-span-1 btn-primary' %>
</div>


<!-- Create a table for displaying contacts -->
<div class="relative overflow-x-auto">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
    <!-- Define table header row -->
    <tr>
      <!-- Column headers for contact attributes -->
      <th scope="col" class="px-6 py-3">First Name</th>
      <th scope="col" class="px-6 py-3">Last Name</th>
      <th scope="col" class="px-6 py-3">Email</th>
      <th scope="col" class="px-6 py-3">Phone</th>
      <th scope="col" class="px-6 py-3">Action</th>
    </tr>
    </thead>
    <tbody>
    <!-- Iterate through each contact in the @contacts list -->
    <% @contacts.each do |contact| %>
      <!-- Create a table row for each contact -->
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <!-- Display contact attributes in corresponding columns -->
        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= contact.first_name %></th>
        <td class="px-6 py-4"><%= contact.last_name %></td>
        <td class="px-6 py-4"><%= contact.email %></td>
        <td class="px-6 py-4"><%= contact.phone %></td>
        <td>
          <!-- Links for showing, editing, and deleting a contact -->
          <%= link_to 'Show', contact_path(contact) %>
          <%= link_to 'Edit', edit_contact_path(contact) %>
          <%= link_to "Destroy", contact_path(contact), data: {
            turbo_method: :delete,   # Specify a Turbo Stream delete method
            turbo_confirm: "Are you sure?"  # Display a confirmation dialog
          } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/contacts/new.html.erb
<h1 class="col-start-1 col-end-3 mb-5">New Contact</h1>

<!--form_with is a rails helper method that creates a form for a model object.
form_with takes a model object and a url (where it will post the data) as arguments.
contacts_path is a rails helper method that returns the path for the contacts create action-->

<%= render 'form' %>

app/views/contacts/show.html.erb
<!-- contacts/show.html.erb -->

<!-- Display the page title -->
<h1 class="col-start-1 col-end-3 mb-5">Contact Details</h1>

<!-- Display contact attributes using @contact instance variable defined inside "show" action -->
<p class="mb-5"><strong class="text-blue-500">First Name:</strong> <%= @contact.first_name %></p>
<p class="mb-5"><strong class="text-blue-500">Last Name:</strong> <%= @contact.last_name %></p>
<p class="mb-5"><strong class="text-blue-500">Email:</strong> <%= @contact.email %></p>
<p class="mb-5"><strong class="text-blue-500">Phone:</strong> <%= @contact.phone %></p>

<div class="mt-5">
  <!-- Link to go back to the contacts list -->
  <%= link_to 'Go Back', contacts_path, class: 'btn-secondary' %>
</div>

app/views/home/dashboard.html.erb
<h1>Dashboard</h1>
<p>My Very First Rails App</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>